# Generated by Django 5.1 on 2024-08-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='remarks',
            field=models.CharField(editable=False, max_length=4),
        ),
    ]
